package com.example.disasternews.fragment;

import java.util.ArrayList;
import java.util.List;

import android.os.Bundle;

import com.example.disasternews.SettingsArrayAdapter;
import com.example.disasternews.models.Country;

public class CountrySettingFragment extends BaseSettingFragment{
	
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		List<Country> countries = new ArrayList<>();
		countries.add(new Country("Select All", false));
		countries.add(new Country("Afghanistan", false));
		countries.add(new Country("Aland Islands", false));
		countries.add(new Country("Albania", false));
		countries.add(new Country("Algeria", false));
		countries.add(new Country("American Samoa", false));
		countries.add(new Country("Andorra", false));
		countries.add(new Country("Anguilla", false));
		countries.add(new Country("Antigua and Barbuda", false));
		countries.add(new Country("Argentina", false));
		countries.add(new Country("Armenia", false));
		countries.add(new Country("Aruba", false));
//		countries.add("Australia");
//		countries.add("Austria");
//		countries.add("Azerbaijan");
//		countries.add("Azores Islands");
//		countries.add("Bahamas");
//		countries.add("Bahrain");
//		countries.add("Bangladesh");
//		countries.add("Barbados");
//		countries.add("Belarus");
//		countries.add("Belgium");
//		countries.add("Belize");
//		countries.add("Benin");
//		countries.add("Bermuda");
//		countries.add("Bhutan");
//		countries.add("Bolivia");
//		countries.add("Botswana");
//		countries.add("Brazil");
//		countries.add("British Virgin Islands");
//		countries.add("Brunei Darussalam");
//		countries.add("Bulgaria");
//		countries.add("Burkina Faso");
//		countries.add("Burundi");
//		countries.add("Cambodia");
//		countries.add("Cameroon");
//		countries.add("Canada");
//		countries.add("Canary Islands");
//		countries.add("Cape Verde");
//		countries.add("Cayman Islands");
//		countries.add("Central African Republic");
//		countries.add("Chad");
//		countries.add("Channel Islands");
//		countries.add("Chile");
//		countries.add("China");
//		countries.add("Christmas Island");
//		countries.add("Cocos (Keeling) Islands");
//		countries.add("Colombia");
//		countries.add("Comoros");
//		countries.add("Congo");
//		countries.add("Cook Islands");
//		countries.add("Costa Rica");
//		countries.add("C��te d'Ivoire");
//		countries.add("Croatia");
//		countries.add("Cuba");
//		countries.add("Cyprus");
//		countries.add("Czech Republic");
//		countries.add("Democratic People's Republic of Korea");
//		countries.add("Democratic Republic of the Congo");
//		countries.add("Denmark");
//		countries.add("Djibouti");
//		countries.add("Dominica");
//		countries.add("Dominican Republic");
//		countries.add("Easter Island");
//		countries.add("Ecuador");
//		countries.add("Egypt");
//		countries.add("El Salvador");
//		countries.add("Equatorial Guinea");
//		countries.add("Eritrea");
//		countries.add("Estonia");
//		countries.add("Ethiopia");
//		countries.add("Falkland Islands (Malvinas)");
//		countries.add("Faroe Islands");
//		countries.add("Fiji");
//		countries.add("Finland");
//		countries.add("France");
//		countries.add("French Guiana");
//		countries.add("French Polynesia");
//		countries.add("French Southern and Antarctic");
//		countries.add("Gabon");
//		countries.add("Galapagos Islands");
//		countries.add("Gambia");
//		countries.add("Georgia");
//		countries.add("Germany");
//		countries.add("Ghana");
//		countries.add("Gibraltar");
//		countries.add("Greece");
//		countries.add("Greenland");
//		countries.add("Grenada");
//		countries.add("Guadeloupe");
//		countries.add("Guam");
//		countries.add("Guatemala");
//		countries.add("Guinea");
//		countries.add("Guinea-Bissau");
//		countries.add("Guyana");
//		countries.add("Haiti");
//		countries.add("Heard Island and McDonald Islands");
//		countries.add("Holy See");
//		countries.add("Honduras");
//		countries.add("Hungary");
//		countries.add("Iceland");
//		countries.add("India");
//		countries.add("Indonesia");
//		countries.add("Iran");
//		countries.add("Iraq");
//		countries.add("Ireland");
//		countries.add("Isle of Man");
//		countries.add("Israel");
//		countries.add("Italy");
//		countries.add("Jamaica");
//		countries.add("Japan");
//		countries.add("Jordan");
//		countries.add("Kazakhstan");
//		countries.add("Kenya");
//		countries.add("Kiribati");
//		countries.add("Kuwait");
//		countries.add("Kyrgyzstan");
//		countries.add("Lao People's Democratic Republic");
//		countries.add("Latvia");
//		countries.add("Lebanon");
//		countries.add("Lesotho");
//		countries.add("Liberia");
//		countries.add("Libya");
//		countries.add("Liechtenstein");
//		countries.add("Lithuania");
//		countries.add("Luxembourg");
//		countries.add("Madagascar");
//		countries.add("Madeira");
//		countries.add("Malawi");
//		countries.add("Malaysia");
//		countries.add("Maldives");
//		countries.add("Mali");
//		countries.add("Malta");
//		countries.add("Marshall Islands");
//		countries.add("Martinique");
//		countries.add("Mauritania");
//		countries.add("Mauritius");
//		countries.add("Mayotte");
//		countries.add("Mexico");
//		countries.add("Micronesia");
//		countries.add("Moldova");
//		countries.add("Monaco");
//		countries.add("Mongolia");
//		countries.add("Montenegro");
//		countries.add("Montserrat");
//		countries.add("Morocco");
//		countries.add("Mozambique");
//		countries.add("Myanmar");
//		countries.add("Namibia");
//		countries.add("Nauru");
//		countries.add("Nepal");
//		countries.add("Netherlands");
//		countries.add("Netherlands Antilles");
//		countries.add("New Caledonia");
//		countries.add("New Zealand");
//		countries.add("Nicaragua");
//		countries.add("Niger");
//		countries.add("Nigeria");
//		countries.add("Niue");
//		countries.add("Norfolk Island");
//		countries.add("Northern Mariana Islands");
//		countries.add("Norway");
//		countries.add("Occupied Palestinian territory");
//		countries.add("Oman");
//		countries.add("Pakistan");
//		countries.add("Palau");
//		countries.add("Panama");
//		countries.add("Papua New Guinea");
//		countries.add("Paraguay");
//		countries.add("Peru");
//		countries.add("Philippines");
//		countries.add("Pitcairn Island");
//		countries.add("Poland");
//		countries.add("Portugal");
//		countries.add("Puerto Rico");
//		countries.add("Qatar");
//		countries.add("Republic of Korea");
//		countries.add("R��union");
//		countries.add("Romania");
//		countries.add("Russian Federation");
//		countries.add("Rwanda");
//		countries.add("Saint Helena");
//		countries.add("Saint Kitts and Nevis");
//		countries.add("Saint Lucia");
//		countries.add("Saint Pierre and Miquelon");
//		countries.add("Saint Vincent and the Grenadines");
//		countries.add("Samoa");
//		countries.add("San Marino");
//		countries.add("Sao Tome and Principe");
//		countries.add("Saudi Arabia");
//		countries.add("Senegal");
//		countries.add("Serbia");
//		countries.add("Seychelles");
//		countries.add("Sierra Leone");
//		countries.add("Singapore");
//		countries.add("Slovakia");
//		countries.add("Slovenia");
//		countries.add("Solomon Islands");
//		countries.add("Somalia");
//		countries.add("South Africa");
//		countries.add("South Sudan");
//		countries.add("Spain");
//		countries.add("Sri Lanka");
//		countries.add("Sudan");
//		countries.add("Suriname");
//		countries.add("Svalbard and Jan Mayen Islands");
//		countries.add("Swaziland");
//		countries.add("Sweden");
//		countries.add("Switzerland");
//		countries.add("Syrian Arab Republic"); 
//		countries.add("Tajikistan");
//		countries.add("Thailand");
//		countries.add("The former Yugoslav Republic of Macedonia");
//		countries.add("Timor-Leste");
//		countries.add("Togo");
//		countries.add("Tokelau");
//		countries.add("Tonga");
//		countries.add("Trinidad and Tobago");
//		countries.add("Tunisia");
//		countries.add("Turkey");
//		countries.add("Turkmenistan");
//		countries.add("Turks and Caicos Islands");
//		countries.add("Tuvalu");
//		countries.add("Uganda");
//		countries.add("Ukraine");
//		countries.add("United Arab Emirates");
//		countries.add("United Kingdom of Great Britain and Northern Ireland");
//		countries.add("United Republic of Tanzania");
//		countries.add("United States of America");
//		countries.add("United States Virgin Islands");
//		countries.add("Uruguay");
//		countries.add("Uzbekistan");
//		countries.add("Vanuatu");
//		countries.add("Venezuela (Bolivarian Republic of)");
//		countries.add("Viet Nam");
//		countries.add("Wallis and Futuna");
//		countries.add("Western Sahara");
//		countries.add("World");
//		countries.add("Yemen");
//		countries.add("Zambia");
//		countries.add("Zimbabwe");
//		
		adapter = new SettingsArrayAdapter(getActivity(), countries);
	}

	public static CountrySettingFragment newInstance() {
		return new CountrySettingFragment();
	}
}
